### PR TITLE
More response code info

### PR DESCRIPTION
**Pull request by dittons**
Here's a function to calculate the response code from the challenge code.
The full list of challenge-response code pairs in your repository made this quite do-able.

### CODE REVIEW

**Comment by dittons** [comment]
Oh the irony - my comment about there perhaps being a typo in elite/zwift code itself has a typo !

**Comment by dittons** [comment]
Oh the irony - my comment about there perhaps being a typo in elite/zwift code itself has a typo !
I'll send a new pull request.

**Comment by Makinolo** [comment]
Hi @dittons , I'm trying to use this code to generate the responses but it does not generate correct codes. 
I've been doing some research and was able to generate some codes with a slight change

int n = (challenge * 3) % 11;

But this only gives me the first 105 codes and some others in between. Makes some sense as 105 = 0x69 and 0xFF - 0x69 = 0x96 which seems like the magic number they are using.
It would be nice if you could tell me what am I missing from this or give me some hints on how you approached the problem.

Thank you!

**Comment by dittons** [comment]
@Makinolo I can try to help if you can me a value for a 'challenge' and the calculated 'response' that you think is incorrect.

**Comment by Makinolo** [comment]
Thank you for your reply @dittons . Never mind about my message. I talked to Keith and the problem was his list of codes was wrong because the endianness was reversed in the decimal list he published. So my test code was checking against a wrong code list 😅 
It works perfect now

**Pull request closed without merging**
